apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: project5-app-reader
  namespace: project5

rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - configmaps
    verbs:
      - get
      - list
      - watch