apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: project5-app-hpa
  namespace: project5

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: project5-app

  minReplicas: 3
  maxReplicas: 4

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
    scaleDown:
      stabilizationWindowSeconds: 0

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50